package com.asn.smvc.test.entities;
// Generated 14 Jun 14 7:23:22 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Skp generated by hbm2java
 */
@Entity
@Table(name = "skp")
public class Skp implements java.io.Serializable {

    private Integer id;
    private Doctor doctor;
    private String namaKegiatan;
    private int jumlahSkp;

    public Skp() {
    }

    public Skp(Doctor doctor, String namaKegiatan, Integer jumlahSkp) {
        this.doctor = doctor;
        this.namaKegiatan = namaKegiatan;
        this.jumlahSkp = jumlahSkp;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "doctor_id", nullable = false)
    public Doctor getDoctor() {
        return this.doctor;
    }

    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    @Column(name = "nama_kegiatan", nullable = false, length = 100)
    public String getNamaKegiatan() {
        return this.namaKegiatan;
    }

    public void setNamaKegiatan(String namaKegiatan) {
        this.namaKegiatan = namaKegiatan;
    }

    @Column(name = "jumlah_skp", nullable = false)
    public Integer getJumlahSkp() {
        return this.jumlahSkp;
    }

    public void setJumlahSkp(Integer jumlahSkp) {
        this.jumlahSkp = jumlahSkp;
    }
}
